.TH "DemoTokenizer.DemoTokenizer" 3 "Tue Dec 6 2022" "Tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemoTokenizer.DemoTokenizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBfmtcharRecog\fP (text)"
.br
.ti -1c
.RI "def \fBperformSentenceSplit\fP (text)"
.br
.ti -1c
.RI "def \fBperformWordSplit\fP (self, text)"
.br
.ti -1c
.RI "def \fBtag\fP (lstData)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def DemoTokenizer\&.DemoTokenizer\&.fmtcharRecog ( text)"

.PP
.nf
This is a function to enable character recognition

.fi
.PP
 
.SS "def DemoTokenizer\&.DemoTokenizer\&.performSentenceSplit ( text)"

.PP
.nf
This is a function to enable sentence splitting in range

.fi
.PP
 
.SS "def DemoTokenizer\&.DemoTokenizer\&.tag ( lstData)"

.PP
.nf
Tagging string and a function to generate a list of colors

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tokenizer from the source code\&.
