.TH "errors.PhraseEndError" 3 "Tue Dec 6 2022" "tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errors.PhraseEndError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBerrors\&.TokenizerError\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
 Sentence doesn't respects the ending condition 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for tokenizer from the source code\&.
