.TH "errors.TokenizerError" 3 "Tue Dec 6 2022" "tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errors.TokenizerError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBerrors\&.PhraseEndError\fP, and \fBerrors\&.PhraseStartError\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
 Base class for exceptions 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for tokenizer from the source code\&.
