.TH "md__r_e_a_d_m_e" 3 "Tue Nov 29 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- natural-english-tokenizer 
.PP
In computer science, lexical analysis, lexing or tokenization is the process of converting a sequence of characters into a sequence of lexical tokens\&.
.SH "Team Members"
.PP
sandrine Awah Nwabufo\&.T\&.Emmanuel Junior 
