.TH "C:/Users/nwabu/Desktop/Emmanuel/FALL 2022/Compiler Construction/Group_22_V/natural-english-tokenizer/README.md" 3 "Tue Dec 6 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nwabu/Desktop/Emmanuel/FALL 2022/Compiler Construction/Group_22_V/natural-english-tokenizer/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
