.TH "sentence.Sentence" 3 "Tue Nov 29 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sentence.Sentence
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsentence_check\fP (text)"
.br
.ti -1c
.RI "list \fBget_token\fP (text)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBf\fP = open('\&./assets/sample\&.txt', 'r')"
.br
.ti -1c
.RI "\fBsample\fP = f\&.read()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " list  sentence\&.Sentence\&.get_token ( text)"

.PP
.nf
This functions splits the sentence into words
.fi
.PP
 
.SS "def sentence\&.Sentence\&.sentence_check ( text)"

.PP
.nf
This function checks if the sentence is proper
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "sentence\&.Sentence\&.f = open('\&./assets/sample\&.txt', 'r')\fC [static]\fP"

.SS "sentence\&.Sentence\&.sample = f\&.read()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
