.TH "statement.statement_tokenizer" 3 "Tue Nov 29 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statement.statement_tokenizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "list \fBget_tokens\fP (self, text)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def statement\&.statement_tokenizer\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS " str statement\&.statement_tokenizer\&.__str__ ( self)"

.SS " list statement\&.statement_tokenizer\&.get_tokens ( self,  text)"


.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
