.TH "statement.py" 3 "Tue Nov 29 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statement.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstatement\&.statement_tokenizer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstatement\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
