.TH "C:/Users/nwabu/Desktop/Emmanuel/FALL 2022/Compiler Construction/Group_22_V/natural-english-tokenizer/statement.py" 3 "Tue Dec 6 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nwabu/Desktop/Emmanuel/FALL 2022/Compiler Construction/Group_22_V/natural-english-tokenizer/statement.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstatement\&.statement_tokenizer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstatement\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
