.TH "C:/Users/nwabu/Desktop/Emmanuel/FALL 2022/Compiler Construction/Group_22_V/natural-english-tokenizer/tokenizer.py" 3 "Tue Dec 6 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nwabu/Desktop/Emmanuel/FALL 2022/Compiler Construction/Group_22_V/natural-english-tokenizer/tokenizer.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtokenizer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtokenizer\&.f\fP = open('\&./assets/sample\&.txt', 'r')"
.br
.ti -1c
.RI "\fBtokenizer\&.sample\fP = f\&.read()"
.br
.ti -1c
.RI "\fBtokenizer\&.tokenizer\fP = Sentence()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
