.TH "tokenizer" 3 "Tue Dec 6 2022" "GROUP_22_V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tokenizer
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBf\fP = open('\&./assets/sample\&.txt', 'r')"
.br
.ti -1c
.RI "\fBsample\fP = f\&.read()"
.br
.ti -1c
.RI "\fBtokenizer\fP = \fBSentence\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tokenizer\&.f = open('\&./assets/sample\&.txt', 'r')"

.SS "tokenizer\&.sample = f\&.read()"

.SS "tokenizer\&.tokenizer = \fBSentence\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for GROUP_22_V from the source code\&.
