.TH "lexical.py" 3 "Mon Dec 12 2022" "natural english language tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lexical.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlexical\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBlexical\&.text\fP = 'Its show time'"
.br
.ti -1c
.RI "list \fBlexical\&.punctuation\fP = ['!', '?',',','\&.',';',':']"
.br
.ti -1c
.RI "list \fBlexical\&.noun\fP = ['+', '\-', '*', '/', '=', '+=', '\-=', '==', '<', '>', '<=', '>=']"
.br
.ti -1c
.RI "list \fBlexical\&.adverb\fP"
.br
.ti -1c
.RI "list \fBlexical\&.verb\fP"
.br
.ti -1c
.RI "list \fBlexical\&.in_adverb\fP = []"
.br
.ti -1c
.RI "list \fBlexical\&.in_spl_punctuation\fP = []"
.br
.ti -1c
.RI "list \fBlexical\&.in_noun\fP = []"
.br
.ti -1c
.RI "list \fBlexical\&.in_verb\fP = []"
.br
.ti -1c
.RI "list \fBlexical\&.in_identifiers\fP = []"
.br
.ti -1c
.RI "list \fBlexical\&.in_constants\fP = []"
.br
.ti -1c
.RI "list \fBlexical\&.tokens\fP = []"
.br
.ti -1c
.RI "bool \fBlexical\&.isStr\fP = False"
.br
.ti -1c
.RI "bool \fBlexical\&.isWord\fP = False"
.br
.ti -1c
.RI "int \fBlexical\&.isCmt\fP = 0"
.br
.ti -1c
.RI "string \fBlexical\&.token\fP = ''"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for natural english language tokenizer from the source code\&.
