.TH "parts_speech.py" 3 "Mon Dec 12 2022" "natural english language tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parts_speech.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBparts_speech\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBparts_speech\&.nouns\fP"
.br
.ti -1c
.RI "list \fBparts_speech\&.verbs\fP"
.br
.ti -1c
.RI "list \fBparts_speech\&.adjectives\fP"
.br
.ti -1c
.RI "list \fBparts_speech\&.adverbs\fP"
.br
.ti -1c
.RI "list \fBparts_speech\&.conjunctions\fP"
.br
.ti -1c
.RI "list \fBparts_speech\&.interjections\fP"
.br
.ti -1c
.RI "list \fBparts_speech\&.pronouns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for natural english language tokenizer from the source code\&.
